- hosts: all
  remote_user: ubuntu
  roles:
    - { role: system-upgrade, tags: ["upgrade"] }
    - { role: geerlingguy.docker, tags: ["install-docker"] }
    - { role: deploy-jenkins, tags: ["deploy-jenkins"] }